apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: garafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ycsto2 # Replace this with the name of your node
  hostPath:
    path: /grafana
