apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb
data:
  DOCKER_INFLUXDB_INIT_MODE: "setup"
  DOCKER_INFLUXDB_INIT_USERNAME: "admin"
  DOCKER_INFLUXDB_INIT_PASSWORD: "Admin"
  DOCKER_INFLUXDB_INIT_ORG: jmeter"
  DOCKER_INFLUXDB_INIT_BUCKET: "jmeter"
  DOCKER_INFLUXDB_INIT_RETENTION: "30d"
