apiVersion: v1
kind: PersistentVolume
metadata:
  name: csv-files-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /jmeter/jmeter-csv # Replace with your desired host path type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ycsto1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
