apiVersion: v1
kind: Service
metadata:
  name: jmeter-slave  # This is the name you'll use in the master
  labels:
    app: jmeter-slave
spec:
  selector:
    app: jmeter-slave
  ports:
    - name: rmi-port
      port: 1099
      targetPort: 1099
    - name: communication-port
      port: 60000
      targetPort: 60000
  clusterIP: None  # This creates a headless service
