apiVersion: v1
kind: PersistentVolume
metadata:
  name: csv-files-pv
  labels:
    app: jmeter-master
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ycsto1  # Ensure this matches your node name exactly
  hostPath:
    path: /jmeter/jmeter-csv  # Path on the specific node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-files-pvc
  labels:
    app: jmeter-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
