apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-vts
  labels:
    app: jmeter-vts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-vts
  template:
    metadata:
      labels:
        app: jmeter-vts
    spec:
      containers:
        - name: jmeter-vts
          image: performancetesting/opentext_vts_linux_ubuntu:24.3
          ports:
            - containerPort: 8080  # Default port used by VTS
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: VTS_HOST
              value: "0.0.0.0"
            - name: VTS_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jmetervts
  labels:
    app: jmeter-vts
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jmeter-vts
  type: ClusterIP
