apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    app: jmeter-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      containers:
        - name: jmeter-master
          image: vybhavkadam1/jmeter:latest
          imagePullPolicy: Always
          env:
            - name: HEAP
              value: -Xms1g -Xmx1g
          ports:
            - containerPort: 1099
            - containerPort: 60000
          volumeMounts:
            - name: test-plan
              mountPath: /test
            - name: csv-files
              mountPath: /csv  # Mounting CSV files from PVC
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          args: ["-n", "-t", "/test/load-test.jmx",
                "-R","jmeter-slave.jmeter", 
                "-r", "-Dserver.rmi.ssl.disable=true", 
                "-Jserver.rmi.localport=60000",  # Ensure this matches RMI port on slave
                "-Jclient.rmi.localport=1099",
                "-e", 
                "-o", "/csv/reports", 
                "-l", "/csv/results.jtl", 
                "-j", "/csv/result.log" ]
      volumes:
        - name: test-plan
          configMap:
            name: jmeter-config
        - name: csv-files
          persistentVolumeClaim:
            claimName: csv-files-pvc
